### ISSUE TITLE
CSS 변경 필요사항 & 주말간 해야할 사항

### ISSUE THREAD

**Issue by osy9757** [hyundai-fruitfruit/frontend#14]
## 구현 사항

- [x] 로그인 캐릭터 바꾸기
- [x] 메인 페이지 캐릭터 화질 수정
- [ ] 조건에 따라 말풍선 멘트수정
- [ ] 클레이모피즘 버튼 스타일 수정
- [ ] 오늘의 랜덤스팟 전체적인 css 수정
- [ ] 모달 생성 삭제 애니메이션추가
- [x] 오늘의 랜덤스팟 소개 가게명 스타일 수정
- [x] 매장 상세페이지 하단 버튼들 css 수정
- [x] 매장 상세페이지 자간 맞추기
- [ ] 리뷰 작성 페이지 사진 첨부버튼 이미지수정
- [ ] 헤더 뒤로가기버튼 css 수정
- [ ] api 연동
- [ ] 메인페이지 글자 크기 조정

---------
- [ ] https 배포 다시 설정,,
- [ ] 어플 로고 바꾸기
- [ ] 어플 실행 초기화면 로고 바꾸기

-----------
- [ ] 매장 상세정보 api 전화번호 0 으로 넘어옴
- [ ] 매장 상세정보에서 해시태그 불러올때 카운트 값 안넘어옴
- [ ] 리뷰 내용 넘어올때 이미지, 유저이름, 날짜, 좋아요 없음, 넘어올때 시간같은 값이 없어서 리뷰가 넘어오는 순서가 불정확한듯
- [ ] #23

**Comment by sangeun99** [comment]
## 2월 26일 제안
### P5
- [ ] 말풍선 글자 크기 줄여주세요
- [ ] 폰트 Pretendard 어떤가요?ㅎㅎ

**Comment by osy9757** [comment]
> ## 2월 26일 제안
> ### P5
> * [ ]  말풍선 글자 크기 줄여주세요
> * [ ]  폰트 Pretendard 어떤가요?ㅎㅎ

앱 전체 폰트 Pretendard로 하라는 건가여??

**Comment by sangeun99** [comment]
![image](https://github.com/hyundai-fruitfruit/frontend/assets/63828057/f5e97105-23ea-4ec1-9529-7021bc0ca435)
